/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MestreRouteImport } from './routes/mestre'
import { Route as MurRouteImport } from './routes/mur'
import { Route as ApiAiEditRouteImport } from './routes/api/ai-edit'
import { Route as ApiPublicAudioIdRouteImport } from './routes/api/public/audio/$id'
import { Route as ApiPublicCoverIdRouteImport } from './routes/api/public/cover/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MestreRoute = MestreRouteImport.update({
  id: '/mestre',
  path: '/mestre',
  getParentRoute: () => rootRouteImport,
} as any)
const MurRoute = MurRouteImport.update({
  id: '/mur',
  path: '/mur',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiEditRoute = ApiAiEditRouteImport.update({
  id: '/api/ai-edit',
  path: '/api/ai-edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAudioIdRoute = ApiPublicAudioIdRouteImport.update({
  id: '/api/public/audio/$id',
  path: '/api/public/audio/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCoverIdRoute = ApiPublicCoverIdRouteImport.update({
  id: '/api/public/cover/$id',
  path: '/api/public/cover/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mestre': typeof MestreRoute
  '/mur': typeof MurRoute
  '/api/ai-edit': typeof ApiAiEditRoute
  '/api/public/audio/$id': typeof ApiPublicAudioIdRoute
  '/api/public/cover/$id': typeof ApiPublicCoverIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mestre': typeof MestreRoute
  '/mur': typeof MurRoute
  '/api/ai-edit': typeof ApiAiEditRoute
  '/api/public/audio/$id': typeof ApiPublicAudioIdRoute
  '/api/public/cover/$id': typeof ApiPublicCoverIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mestre': typeof MestreRoute
  '/mur': typeof MurRoute
  '/api/ai-edit': typeof ApiAiEditRoute
  '/api/public/audio/$id': typeof ApiPublicAudioIdRoute
  '/api/public/cover/$id': typeof ApiPublicCoverIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mestre'
    | '/mur'
    | '/api/ai-edit'
    | '/api/public/audio/$id'
    | '/api/public/cover/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mestre'
    | '/mur'
    | '/api/ai-edit'
    | '/api/public/audio/$id'
    | '/api/public/cover/$id'
  id:
    | '__root__'
    | '/'
    | '/mestre'
    | '/mur'
    | '/api/ai-edit'
    | '/api/public/audio/$id'
    | '/api/public/cover/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MestreRoute: typeof MestreRoute
  MurRoute: typeof MurRoute
  ApiAiEditRoute: typeof ApiAiEditRoute
  ApiPublicAudioIdRoute: typeof ApiPublicAudioIdRoute
  ApiPublicCoverIdRoute: typeof ApiPublicCoverIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mestre': {
      id: '/mestre'
      path: '/mestre'
      fullPath: '/mestre'
      preLoaderRoute: typeof MestreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mur': {
      id: '/mur'
      path: '/mur'
      fullPath: '/mur'
      preLoaderRoute: typeof MurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-edit': {
      id: '/api/ai-edit'
      path: '/api/ai-edit'
      fullPath: '/api/ai-edit'
      preLoaderRoute: typeof ApiAiEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/audio/$id': {
      id: '/api/public/audio/$id'
      path: '/api/public/audio/$id'
      fullPath: '/api/public/audio/$id'
      preLoaderRoute: typeof ApiPublicAudioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cover/$id': {
      id: '/api/public/cover/$id'
      path: '/api/public/cover/$id'
      fullPath: '/api/public/cover/$id'
      preLoaderRoute: typeof ApiPublicCoverIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MestreRoute: MestreRoute,
  MurRoute: MurRoute,
  ApiAiEditRoute: ApiAiEditRoute,
  ApiPublicAudioIdRoute: ApiPublicAudioIdRoute,
  ApiPublicCoverIdRoute: ApiPublicCoverIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
