/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AjudaRouteImport } from './routes/ajuda'
import { Route as CoordinadorRouteImport } from './routes/coordinador'
import { Route as EspaiRouteImport } from './routes/espai'
import { Route as EstudiRouteImport } from './routes/estudi'
import { Route as MestreRouteImport } from './routes/mestre'
import { Route as MurRouteImport } from './routes/mur'
import { Route as PrivacitatRouteImport } from './routes/privacitat'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as TermesRouteImport } from './routes/termes'
import { Route as ApiAiEditRouteImport } from './routes/api/ai-edit'
import { Route as ClasseCodeRouteImport } from './routes/classe.$code'
import { Route as EscolaSlugRouteImport } from './routes/escola.$slug'
import { Route as ApiPublicAudioIdRouteImport } from './routes/api/public/audio/$id'
import { Route as ApiPublicCoverIdRouteImport } from './routes/api/public/cover/$id'
import { Route as ApiPublicSoundIdRouteImport } from './routes/api/public/sound/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaRoute = AjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const CoordinadorRoute = CoordinadorRouteImport.update({
  id: '/coordinador',
  path: '/coordinador',
  getParentRoute: () => rootRouteImport,
} as any)
const EspaiRoute = EspaiRouteImport.update({
  id: '/espai',
  path: '/espai',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudiRoute = EstudiRouteImport.update({
  id: '/estudi',
  path: '/estudi',
  getParentRoute: () => rootRouteImport,
} as any)
const MestreRoute = MestreRouteImport.update({
  id: '/mestre',
  path: '/mestre',
  getParentRoute: () => rootRouteImport,
} as any)
const MurRoute = MurRouteImport.update({
  id: '/mur',
  path: '/mur',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacitatRoute = PrivacitatRouteImport.update({
  id: '/privacitat',
  path: '/privacitat',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const TermesRoute = TermesRouteImport.update({
  id: '/termes',
  path: '/termes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiEditRoute = ApiAiEditRouteImport.update({
  id: '/api/ai-edit',
  path: '/api/ai-edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ClasseCodeRoute = ClasseCodeRouteImport.update({
  id: '/classe/$code',
  path: '/classe/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const EscolaSlugRoute = EscolaSlugRouteImport.update({
  id: '/escola/$slug',
  path: '/escola/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAudioIdRoute = ApiPublicAudioIdRouteImport.update({
  id: '/api/public/audio/$id',
  path: '/api/public/audio/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCoverIdRoute = ApiPublicCoverIdRouteImport.update({
  id: '/api/public/cover/$id',
  path: '/api/public/cover/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSoundIdRoute = ApiPublicSoundIdRouteImport.update({
  id: '/api/public/sound/$id',
  path: '/api/public/sound/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/coordinador': typeof CoordinadorRoute
  '/espai': typeof EspaiRoute
  '/estudi': typeof EstudiRoute
  '/mestre': typeof MestreRoute
  '/mur': typeof MurRoute
  '/privacitat': typeof PrivacitatRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/superadmin': typeof SuperadminRoute
  '/termes': typeof TermesRoute
  '/api/ai-edit': typeof ApiAiEditRoute
  '/classe/$code': typeof ClasseCodeRoute
  '/escola/$slug': typeof EscolaSlugRoute
  '/api/public/audio/$id': typeof ApiPublicAudioIdRoute
  '/api/public/cover/$id': typeof ApiPublicCoverIdRoute
  '/api/public/sound/$id': typeof ApiPublicSoundIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/coordinador': typeof CoordinadorRoute
  '/espai': typeof EspaiRoute
  '/estudi': typeof EstudiRoute
  '/mestre': typeof MestreRoute
  '/mur': typeof MurRoute
  '/privacitat': typeof PrivacitatRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/superadmin': typeof SuperadminRoute
  '/termes': typeof TermesRoute
  '/api/ai-edit': typeof ApiAiEditRoute
  '/classe/$code': typeof ClasseCodeRoute
  '/escola/$slug': typeof EscolaSlugRoute
  '/api/public/audio/$id': typeof ApiPublicAudioIdRoute
  '/api/public/cover/$id': typeof ApiPublicCoverIdRoute
  '/api/public/sound/$id': typeof ApiPublicSoundIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/coordinador': typeof CoordinadorRoute
  '/espai': typeof EspaiRoute
  '/estudi': typeof EstudiRoute
  '/mestre': typeof MestreRoute
  '/mur': typeof MurRoute
  '/privacitat': typeof PrivacitatRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/superadmin': typeof SuperadminRoute
  '/termes': typeof TermesRoute
  '/api/ai-edit': typeof ApiAiEditRoute
  '/classe/$code': typeof ClasseCodeRoute
  '/escola/$slug': typeof EscolaSlugRoute
  '/api/public/audio/$id': typeof ApiPublicAudioIdRoute
  '/api/public/cover/$id': typeof ApiPublicCoverIdRoute
  '/api/public/sound/$id': typeof ApiPublicSoundIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajuda'
    | '/coordinador'
    | '/espai'
    | '/estudi'
    | '/mestre'
    | '/mur'
    | '/privacitat'
    | '/sitemap.xml'
    | '/superadmin'
    | '/termes'
    | '/api/ai-edit'
    | '/classe/$code'
    | '/escola/$slug'
    | '/api/public/audio/$id'
    | '/api/public/cover/$id'
    | '/api/public/sound/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajuda'
    | '/coordinador'
    | '/espai'
    | '/estudi'
    | '/mestre'
    | '/mur'
    | '/privacitat'
    | '/sitemap.xml'
    | '/superadmin'
    | '/termes'
    | '/api/ai-edit'
    | '/classe/$code'
    | '/escola/$slug'
    | '/api/public/audio/$id'
    | '/api/public/cover/$id'
    | '/api/public/sound/$id'
  id:
    | '__root__'
    | '/'
    | '/ajuda'
    | '/coordinador'
    | '/espai'
    | '/estudi'
    | '/mestre'
    | '/mur'
    | '/privacitat'
    | '/sitemap.xml'
    | '/superadmin'
    | '/termes'
    | '/api/ai-edit'
    | '/classe/$code'
    | '/escola/$slug'
    | '/api/public/audio/$id'
    | '/api/public/cover/$id'
    | '/api/public/sound/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjudaRoute: typeof AjudaRoute
  CoordinadorRoute: typeof CoordinadorRoute
  EspaiRoute: typeof EspaiRoute
  EstudiRoute: typeof EstudiRoute
  MestreRoute: typeof MestreRoute
  MurRoute: typeof MurRoute
  PrivacitatRoute: typeof PrivacitatRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SuperadminRoute: typeof SuperadminRoute
  TermesRoute: typeof TermesRoute
  ApiAiEditRoute: typeof ApiAiEditRoute
  ClasseCodeRoute: typeof ClasseCodeRoute
  EscolaSlugRoute: typeof EscolaSlugRoute
  ApiPublicAudioIdRoute: typeof ApiPublicAudioIdRoute
  ApiPublicCoverIdRoute: typeof ApiPublicCoverIdRoute
  ApiPublicSoundIdRoute: typeof ApiPublicSoundIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda': {
      id: '/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coordinador': {
      id: '/coordinador'
      path: '/coordinador'
      fullPath: '/coordinador'
      preLoaderRoute: typeof CoordinadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espai': {
      id: '/espai'
      path: '/espai'
      fullPath: '/espai'
      preLoaderRoute: typeof EspaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudi': {
      id: '/estudi'
      path: '/estudi'
      fullPath: '/estudi'
      preLoaderRoute: typeof EstudiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mestre': {
      id: '/mestre'
      path: '/mestre'
      fullPath: '/mestre'
      preLoaderRoute: typeof MestreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mur': {
      id: '/mur'
      path: '/mur'
      fullPath: '/mur'
      preLoaderRoute: typeof MurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacitat': {
      id: '/privacitat'
      path: '/privacitat'
      fullPath: '/privacitat'
      preLoaderRoute: typeof PrivacitatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termes': {
      id: '/termes'
      path: '/termes'
      fullPath: '/termes'
      preLoaderRoute: typeof TermesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-edit': {
      id: '/api/ai-edit'
      path: '/api/ai-edit'
      fullPath: '/api/ai-edit'
      preLoaderRoute: typeof ApiAiEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classe/$code': {
      id: '/classe/$code'
      path: '/classe/$code'
      fullPath: '/classe/$code'
      preLoaderRoute: typeof ClasseCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escola/$slug': {
      id: '/escola/$slug'
      path: '/escola/$slug'
      fullPath: '/escola/$slug'
      preLoaderRoute: typeof EscolaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/audio/$id': {
      id: '/api/public/audio/$id'
      path: '/api/public/audio/$id'
      fullPath: '/api/public/audio/$id'
      preLoaderRoute: typeof ApiPublicAudioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cover/$id': {
      id: '/api/public/cover/$id'
      path: '/api/public/cover/$id'
      fullPath: '/api/public/cover/$id'
      preLoaderRoute: typeof ApiPublicCoverIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sound/$id': {
      id: '/api/public/sound/$id'
      path: '/api/public/sound/$id'
      fullPath: '/api/public/sound/$id'
      preLoaderRoute: typeof ApiPublicSoundIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjudaRoute: AjudaRoute,
  CoordinadorRoute: CoordinadorRoute,
  EspaiRoute: EspaiRoute,
  EstudiRoute: EstudiRoute,
  MestreRoute: MestreRoute,
  MurRoute: MurRoute,
  PrivacitatRoute: PrivacitatRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SuperadminRoute: SuperadminRoute,
  TermesRoute: TermesRoute,
  ApiAiEditRoute: ApiAiEditRoute,
  ClasseCodeRoute: ClasseCodeRoute,
  EscolaSlugRoute: EscolaSlugRoute,
  ApiPublicAudioIdRoute: ApiPublicAudioIdRoute,
  ApiPublicCoverIdRoute: ApiPublicCoverIdRoute,
  ApiPublicSoundIdRoute: ApiPublicSoundIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
